### ISSUE TITLE
second sentence of the introductory 

### ISSUE THREAD

**Issue by cpanse** [cpanse/2023-EuBIC-MS-proc#3]
The second sentence of the introductory paragraph of section 3 could have a better punctuation or maybe be split in two sentences.

**Comment by brvpuyve** [comment]
@cpanse I asked Tanja about another picture but she did not have one with her poster. Should I ask for her poster, maybe we can put it aside her picture?

**Comment by brvpuyve** [comment]
Preprint of Tanja her paper which is currently under review: 
The Peptonizer2000: graphical model based taxonomic identifications of metaproteomic samples
Tanja Holstein, Pieter Verschaffelt, Tim Van den Bossche, Lennart Martens, Thilo Muth
bioRxiv 2024.05.20.594958; doi: https://doi.org/10.1101/2024.05.20.594958
