### ISSUE TITLE
The description of hackathons could be more homogeneous

### ISSUE THREAD

**Issue by cpanse** [cpanse/2023-EuBIC-MS-proc#4]
The description of hackathons could be more homogeneous. Even though the writing may closely derive from an abstract written by a different author/organizer, it should have a common section each time: e.g. a small indication on the progress of the project during the meeting. This could help the reader understand the possibilities offered by this kind of session.

**Comment by mmattano** [comment]
For the metabolomics hackathon you can add


During this hackathon, different spectral similarity scoring functions were compared and their target and off-target scores were evaluated based on similarity of the compounds.

**Comment by brvpuyve** [comment]
Input for the hackathon of Tim Van Den Bossche: 
During the hackathon, we developed a prototype tool named Pathway Pilot. This tool features a user-friendly interface designed for exploring and visualizing metabolic pathways identified in metaproteomic samples.

**Comment by MatthewThe** [comment]
For the interactive HTML plots:

During the hackathon, five teams employed pair programming techniques to each develop a new component for a fundamental plot type: histogram, bar plot, swarm plot, violin plot, and line plot. Each team successfully produced a functional component, complete with customization options and unit tests. These components are now available from the node package manager (npm) as part of the @biowc organization.

**Comment by di-hardt** [comment]
For Rusteomics:

During the hackathon the participants build the basis for a community driven mass-spectrometry based proteomics framework written in Rust, starting with prototypes for a spectral library writer and a FASTA reader, including easy to use Python bindings.

**Comment by LLautenbacher** [comment]
During the hackathon we established the framework of the model hosting platform and started adding multiple popular machine learning models. Including Prosit, AlphaPeptDeep, MS2PIP and DeepLC.
